<flat-interpretation-configuration> ::=
     {
        <bed-or-fasta>,
        "model-file" : <file-name>,
        "input-length" : <integer>,
        "output-length" : <integer>,
        "heads" : <integer>,
        "head-id" : <integer>
        "profile-task-ids" : [<list-of-integer>],
        "profile-h5" : <file-name>,
        "counts-h5" : <file-name>,
        "num-shuffles" : <integer>,
        <kmer-size-section>
        <verbosity-section>
    }

<bed-or-fasta> ::=
    "genome" : <file-name>,
    "bed-file" : <file-name>
 |  "fasta-file" : <file-name>
  « "coordinates": {
        "genome" : <file-name>,
        "bed-file" : <file-name>}
  »

<kmer-size-section> ::=
    "kmer-size" : <integer>,
  | <empty>
