<pisa-fasta-configuration> ::=
    {"model-file" : <file-name>,
     "sequence-fasta" : <file-name>,
     "num-shuffles" : <integer>,
     "head-id" : <integer>,
     "task-id" : <integer>,
     "output-h5" : <file-name>,
     "output-length" : <integer>,
     "input-length" : <integer>,
     <verbosity-section>}
