<prediction-fasta-input-configuration> ::=
    { <prediction-fasta-settings-section>,
      <prediction-fasta-input-section>,
      <prediction-fasta-threads-section>
      <verbosity-section> }

<prediction-fasta-settings-section> ::=
    "settings" : {
        "output-h5" : <file-name>,
        "batch-size" : <integer>,
        "heads" : <integer>,
        "architecture" : <prediction-model-settings> }

<prediction-fasta-input-section> ::=
    "fasta-file" : <file-name>

<prediction-fasta-threads-section> ::=
    "num-threads" : <integer>,
  | <empty>
