<prepare-data-configuration> ::=
    {
        "genome" : <file-name>,
        "input-length" : <integer>,
        "output-length" : <integer>,
        "max-jitter" : <integer>,
        "regions" : <file-name>,
        "output-h5" : <file-name>,
        "reverse-complement" : <boolean>,
        "heads" : [<prepare-data-heads-list>],
        <verbosity-section>
    }

<prepare-data-heads-list> ::=
   <prepare-data-individual-head>«, <prepare-data-heads-list>»

<prepare-data-individual-head> ::=
    {
        «<revcomp-head-section>»
        "bigwig-files" : [<list-of-bigwig-file-names>]
    }

<revcomp-head-section> ::=
  | "revcomp-task-order" : "auto",
  | "revcomp-task-order" : [<list-of-integer>],

<list-of-bigwig-file-names> ::=
   <file-name>«, <file-name>»
