#!/usr/bin/env python3
import h5py
import pyBigWig
import scipy.special
import numpy as np
import argparse
import logging
import tqdm
def writeBigWig(inH5, outFname, headId, taskId, mode, verbose):
    logging.info("Starting to write {0:s}, head {1:d} task {2:d}".format(outFname, headId, taskId))
    bwHeader = []
    nameToNum = dict()
    for i, name in enumerate(inH5["chrom_names"].asstr()):
        bwHeader.append(("{0:s}".format(name), inH5['chrom_sizes'][i]))
    outBw = pyBigWig.open(outFname, 'w')

    outBw.addHeader(bwHeader)
    logging.debug(bwHeader)
    logging.info("Added header.")
    numRegions = inH5['coords_chrom'].shape[0]
    #Sort the regions. 
    regionOrder = sorted(range(numRegions), key = lambda x: (inH5['coords_chrom'][x], inH5['coords_start'][x]))
    logging.info("Region order calculated.")
    curChrom = 0
    startWritingAt = 0
    regionID = regionOrder[0]
    regionChrom = inH5['coords_chrom'][regionID]
    regionStart = inH5['coords_start'][regionID]
    regionStop = inH5['coords_stop'][regionID]
    logging.info("Starting to write data.")
    if(verbose):
        regionRange = tqdm.tqdm(range(numRegions))
    else:
        regionRange = range(numRegions)
    for regionNumber in regionRange:
        #Extract the appropriate region from the sorted list. 

        if(regionChrom != curChrom):
            curChrom = regionChrom
            startWritingAt = 0

        if(startWritingAt < regionStart):
            #The next region starts beyond the end 
            #of the previous one. Some bases will not be filled in.
            startWritingAt = regionStart
        #By default, write the whole region. 
        stopWritingAt = regionStop
        #As long as we aren't on the last region, check for overlaps.
        if(regionNumber < numRegions-1):
            nextRegion = regionOrder[regionNumber+1]
            nextChrom = inH5['coords_chrom'][nextRegion]
            nextStart = inH5['coords_start'][nextRegion]
            nextStop = inH5['coords_stop'][nextRegion]
            if(nextChrom == regionChrom and nextStart < stopWritingAt):
                #The next region overlaps. So stop writing before then. 
                overlapSize = regionStop - nextStart
                stopWritingAt = stopWritingAt - overlapSize //2
        dataSliceStart = startWritingAt - regionStart
        dataSliceStop = stopWritingAt - regionStart
        
        #Okay, now it's time to actually do the thing to the data! 
        head = inH5['head_{0:d}'.format(headId)]
        match mode:
            case 'profile':
                logits = head['logits'][regionID]
                #Logits will have shape (output-width x numTasks)
                logCounts = head['logcounts'][regionID]
                profileProb = scipy.special.softmax(logits)
                profile = profileProb * np.exp(logCounts)
                taskProfile = profile[:,taskId]
                profile = taskProfile
            case 'logits':
                profile = head['logits'][regionID, :, taskId]
            case 'logcounts':
                profile = np.zeros((regionStop - regionStart)) + head['logcounts'][regionID]
            case 'counts':
                profile = np.zeros((regionStop - regionStart)) + np.exp(head['logcounts'][regionID])
        

        #print("Adding at {0:d} - {1:d} ({2:d} - {3:d})".format(startWritingAt, stopWritingAt, dataSliceStart, dataSliceStop))
        vals = [float(x) for x in profile[dataSliceStart:dataSliceStop]]
        #print(vals[:10])
        try:
            if(startWritingAt == 0):
                raise RuntimeError()
            outBw.addEntries(bwHeader[regionChrom][0], 
                    startWritingAt,
                    values = vals,
                    span=1, step=1)
        except RuntimeError as e:
            print(e)
            print(startWritingAt)
            print(bwHeader[regionChrom][0])
            print(regionID)
            print(nextRegion)
            print(regionStart)
            print(nextStart)
            print(regionStop)
            print(nextStop)
            print(regionChrom)
            print(nextChrom)
            raise

        #Update the region. By pulling the first setting of the region variables out of the loop,
        #I avoid double-dipping to get those data from the H5. 
        startWritingAt = stopWritingAt
        regionID = nextRegion
        regionChrom = nextChrom
        regionStart = nextStart
        regionStop = nextStop
    logging.info("Closing bigwig.")
    outBw.close()
    logging.info("Bigwig closed.")

def main():
    parser = argparse.ArgumentParser(description='Take an hdf5-format file generated by the predict script and render it to a bigwig.')
    parser.add_argument("--h5", help='The name of the hdf5-format file to be read in.')
    parser.add_argument("--bw", help='The name of the bigwig file that should be written.')
    parser.add_argument("--head-id", help="Which head number do you want data for?", dest='headId', type=int)
    parser.add_argument("--task-id", help='Which task in that head do you want?', dest='taskId', type=int)
    parser.add_argument("--mode", help='What do you want written? Options are "profile", meaning you want (softmax(logits) * exp(logcounts)), or "logits", meaning you just want logits, or "logcounts", meaning you want the log counts for every region, or "counts", meaning you want exp(logcounts). You will usually want "profile"')
    parser.add_argument("--verbose", help="Display progress as the file is being written.", action='store_true')
    args = parser.parse_args()
    if(args.verbose):
        logging.basicConfig(level=logging.INFO)
    else:
        logging.basicConfig(level=logging.WARNING)
    inH5 = h5py.File(args.h5, 'r')
    writeBigWig(inH5, args.bw, args.headId, args.taskId, args.mode, args.verbose)

if(__name__ == "__main__"):
    main()


